server:
    port: 8080

spring:
    application:
        name: producer-service
    cloud:
        stream:
            bindings:
                sendMessage-out-0:
                    destination: message-queue

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        connection-timeout: 10s
